modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/Laz-The-Artist/GardenArsenal/issues"
license = "GNU GENERAL PUBLIC LICENSE version 2"

[[mods]]
modId = "gardenarsenal"
version = "${version}"
displayName = "Garden Arsenal"
authors = "LazTheArtist, CatCore, Boblovespi"
description = '''
Garden Arsenal is mod made by MultiTeam; Its all about guns and weapons that shoot vegetables and edible stuff.

Everything from v0.1.0 and v0.2.0 is here, on a new minecraft version!
Fresh and new all hand-written code, combined with all the new and remade assets!

To be apart of our community, join the discord server!
https://discord.gg/JTwmz8S
'''
credits = "A mod made by MultiTeam"
logoFile="gardenarsenal_icon.png"

[[dependencies.gardenarsenal]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gardenarsenal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gardenarsenal]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"